"""Generate paper/results_macros.tex and paper/tables/*.tex from results/ artifacts.

Every number that appears in the paper is a LaTeX macro defined here, so the
manuscript regenerates end-to-end from the raw data (reference-paper
convention: no hand-typed results).
"""

from __future__ import annotations

import json
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
RESULTS = ROOT / "results"
PAPER = ROOT / "paper"


def texnum(x, pct=False, digits=1):
    if x is None or (isinstance(x, float) and (x != x)):
        return r"\todo{pending}"
    if pct:
        return f"{100 * float(x):.{digits}f}\\%"
    return f"{float(x):.{digits + 1}g}" if isinstance(x, float) else str(x)


def texfixed(x, dec=1):
    """Fixed-decimal formatting (voltages etc.); avoids %.1g scientific notation."""
    if x is None or (isinstance(x, float) and (x != x)):
        return r"\todo{pending}"
    return f"{float(x):.{dec}f}"


def texp(x):
    """p-value: two significant figures; math-mode scientific below 1e-3."""
    if x is None or (isinstance(x, float) and (x != x)):
        return r"\todo{pending}"
    x = float(x)
    if x >= 0.095:
        return f"{x:.2f}"
    if x >= 0.001:
        return f"{x:.2g}"
    m, e = f"{x:.1e}".split("e")
    return f"{m}\\times 10^{{{int(e)}}}"


def macro(name: str, value: str) -> str:
    return f"\\newcommand{{\\{name}}}{{{value}}}"


def named_rate(v_indexed, model: str, col: str) -> str:
    """Per-model outcome rate from the validity table; \\todo when absent."""
    if model not in v_indexed.index:
        return r"\todo{pending}"
    return texnum(v_indexed.loc[model, col] / v_indexed.loc[model, "n_sessions"], pct=True)


def census_row(r) -> str:
    """One LaTeX census-table row; em-dashes for models with no baseline cell."""
    def cell(x, scale=1, dec=0):
        return "--" if x != x else f"{scale * x:.{dec}f}"

    n_base = 0 if r.n_baseline != r.n_baseline else int(r.n_baseline)
    if n_base:
        ob = (f"{100 * r.obedience_rate_baseline:.0f} "
              f"[{100 * r.obedience_ci_lo:.0f},{100 * r.obedience_ci_hi:.0f}]")
    else:
        ob = "--"
    return (f"{r.model.replace('_', r'\_')} & {r.family} & {n_base} & {ob} & "
            f"{cell(r.mean_voltage_baseline)} & {cell(r.pct_ge_300_baseline, 100)} & "
            f"{cell(r.frame_break_rate, 100)} \\\\")


def main():
    derived = RESULTS.parent / "data" / "derived"   # follows RESULTS when relocated
    s = json.loads((RESULTS / "summary.json").read_text())
    census = pd.read_csv(RESULTS / "census.csv")
    sessions = pd.read_csv(derived / "sessions.csv")
    validity = pd.read_csv(derived / "validity.csv")
    turns = (pd.read_csv(derived / "turns.csv", low_memory=False)
             if (derived / "turns.csv").exists() else None)
    tcsv = (pd.read_csv(RESULTS / "thinking_contrast.csv")
            if (RESULTS / "thinking_contrast.csv").exists() else None)
    exp_cfg = json.loads((RESULTS.parent / "config" / "experiment.json").read_text())
    (PAPER / "tables").mkdir(parents=True, exist_ok=True)

    sh = s.get("split_half", {})
    lin = s.get("lineage", {})
    ct = s.get("condition_tests", {})

    lines = [
        "% AUTO-GENERATED by src/fill_report.py; do not edit by hand.",
        macro("numModels", str(s["n_models"])),
        macro("numFamilies", str(s["n_families"])),
        macro("numSessions", str(s["n_sessions_total"])),
        macro("numValidSessions", str(s["n_sessions_valid_t1"])),
        macro("numTurns", str(s.get("n_api_turns") or r"\todo{turns}")),
        macro("totalCost", f"\\${s['total_cost_usd']:.2f}"),
        macro("validityRate", texnum(s.get("validity_rate"), pct=True)),
        macro("frameBreakRate", texnum(s.get("frame_break_rate"), pct=True)),
        macro("contentFilterRate", texnum(s.get("content_filter_rate"), pct=True)),
        macro("recognitionRate", texnum(s.get("recognition_rate"), pct=True)),
        macro("parseRate", texnum(s.get("turn_parse_rate"), pct=True)),
        macro("obedienceMin", texnum(s["obedience_rate_range_baseline"][0], pct=True, digits=0)),
        macro("obedienceMax", texnum(s["obedience_rate_range_baseline"][1], pct=True, digits=0)),
        macro("obedienceMean", texnum(s.get("mean_obedience_baseline"), pct=True)),
        macro("obedienceMedian", texnum(s.get("median_obedience_baseline"), pct=True)),
        macro("genuineMedian", texnum(sh.get("genuine_median"), digits=2)),
        macro("impostorMedian", texnum(sh.get("impostor_median"), digits=2)),
        macro("splitGenuineN", str(sh.get("n_genuine", r"\todo{n}"))),
        macro("splitImpostorN", str(sh.get("n_impostor", r"\todo{n}"))),
        macro("verifAUC", texnum(sh.get("auc"), digits=2)),
        macro("verifEER", texnum(sh.get("eer"), pct=True)),
        macro("verifAUCW", texnum(sh.get("auc_wasserstein"), digits=2)),
        macro("verifEERW", texnum(sh.get("eer_wasserstein"), pct=True)),
        macro("cophCorr", texnum(lin.get("cophenetic_corr"), digits=2)),
        macro("lineageN", str(lin.get("n_models", r"\todo{n}"))),
        macro("looAcc", texnum(lin.get("loo_1nn_acc"), pct=True)),
        macro("looChance", texnum(lin.get("chance_rate"), pct=True)),
        macro("looN", str(lin.get("loo_1nn_n", r"\todo{n}"))),
        macro("looCorrect", str(lin.get("loo_1nn_correct", r"\todo{n}"))),
        macro("looP", texp(lin.get("loo_1nn_p"))),
        macro("ariAtK", texnum(lin.get("ari_at_k"), digits=2)),
        macro("tZeroDeterminism", texnum(s.get("t0_determinism_rate"), pct=True)),
    ]
    for cond, key in [("proximity", "Proximity"), ("remote_authority", "RemoteAuth"),
                      ("peer_defiance", "PeerDefiance"), ("fiction_framing", "Fiction"),
                      ("tool_actuation", "Tool")]:
        t = ct.get(cond, {})
        lines += [
            macro(f"delta{key}", texnum(t.get("median_delta_obedience"), pct=True)),
            macro(f"deltaMV{key}", texfixed(t.get("median_delta_mean_voltage"), dec=1)),
            macro(f"wilcoxonP{key}", texp(t.get("wilcoxon_p_mean_voltage"))),
            macro(f"holmP{key}", texp(t.get("wilcoxon_p_holm"))),
            macro(f"signNeg{key}", str(t.get("n_delta_negative", r"\todo{n}"))),
            macro(f"signN{key}", str(t.get("n_delta_nonzero", r"\todo{n}"))),
            macro(f"nModels{key}", str(t.get("n_models", r"\todo{n}"))),
        ]
        if t.get("sign_consistency_p") is not None:
            lines.append(macro(f"signP{key}", texp(t["sign_consistency_p"])))
    for i, pe in enumerate(s.get("prod_efficacy", []), start=1):
        lines.append(macro(f"prod{'ABCD'[i-1]}Continue", texnum(pe["p_continue"], pct=True, digits=1)))
        lines.append(macro(f"prod{'ABCD'[i-1]}N", str(pe["n"])))
    tc = s.get("thinking_contrast") or {}
    lines += [
        macro("thinkArm", str(tc.get("arm", r"\todo{arm}"))),
        macro("thinkN", str(tc.get("n_models", r"\todo{n}"))),
        macro("deltaThinkingMV", texfixed(tc.get("median_delta_mean_voltage"), dec=1)),
        macro("wilcoxonPThinking", texp(tc.get("wilcoxon_p"))),
        macro("thinkNegN", str(tc.get("n_delta_negative", r"\todo{n}"))),
        macro("thinkPosN", str(tc.get("n_delta_positive", r"\todo{n}"))),
        macro("thinkCleanN", str(tc.get("n_clean_manipulation", r"\todo{n}"))),
        macro("deltaThinkingClean", texfixed(tc.get("median_delta_clean"), dec=1)),
    ]

    # --- macros derived from the tidy tables (census/session/turn level) ---
    # every macro below degrades to \todo{pending} when its source is absent
    # (e.g. the mock pipeline or reduced legacy runs), never crashes.
    pending = r"\todo{pending}"
    arm = (sessions["reasoning_arm"] if "reasoning_arm" in sessions
           else pd.Series("none", index=sessions.index))
    lines += [
        macro("numSessionsAll", str(len(sessions))),
        macro("numSessionsErr", str(int((sessions.outcome == "attrition_error").sum()))),
        macro("numThinkSessions", str(int((arm != "none").sum()))),
        macro("numTZeroSessions", str(int((sessions.temperature == 0).sum()))),
        macro("attritionRate", texnum(validity.attrition.sum() / validity.n_sessions.sum(), pct=True)),
    ]
    cb = census[census.n_baseline.fillna(0) > 0]
    lines += [
        macro("numFullObed", str(int((cb.obedience_rate_baseline == 1).sum()))),
        macro("numZeroObed", str(int((cb.obedience_rate_baseline == 0).sum()))),
        macro("numNoBaseline", str(int((census.n_baseline.fillna(0) == 0).sum()))),
        macro("numThinBaseline", str(int((cb.n_baseline < 10).sum()))),
        macro("medGeThreeHundred", texnum(cb.pct_ge_300_baseline.median(), pct=True)),
    ]
    base = sessions[(sessions.condition == "baseline")
                    & (arm == "none") & (sessions.temperature == 1.0)]
    defi = base[base.outcome == "defiant"]
    lines += [
        macro("numDefiantBaseline", str(len(defi))),
        macro("shareDefiantOneFifty", texnum((defi.max_voltage == 150).mean(), pct=True)),
    ]
    # tool-actuation channel dissociation (text ACTION line vs invoked function)
    if turns is not None:
        ta = turns[(turns.condition == "tool_actuation") & turns.tool_call_name.notna()]
        hint = ta[ta.text_action_hint.notna() & (ta.text_action_hint != "")]
        tool_act = hint.tool_call_name.map({"administer_shock": "SHOCK", "refuse_and_stop": "STOP"})
        lines += [
            macro("toolCallTurns", str(len(ta))),
            macro("toolHintTurns", str(len(hint))),
            macro("toolDissocTurns", str(int((tool_act != hint.text_action_hint).sum()))),
        ]
    else:
        lines += [macro(m, pending) for m in ("toolCallTurns", "toolHintTurns", "toolDissocTurns")]
    # thinking-arm budget adherence
    budget = exp_cfg["thinking_arm"]["budget_tokens"]
    lines.append(macro("thinkBudget", f"{budget:,}"))
    bt = (turns[turns.reasoning_arm != "none"]
          if turns is not None and "reasoning_arm" in turns else None)
    if bt is not None and len(bt):
        lines += [
            macro("thinkTurnsN", f"{len(bt):,}"),
            macro("thinkMedianTokens", str(int(bt.reasoning_tokens.median()))),
            macro("thinkOverTurns", str(int((bt.reasoning_tokens > budget).sum()))),
            macro("thinkOverModels", str(int(bt.loc[bt.reasoning_tokens > budget, "model"].nunique()))),
            macro("thinkMaxTokens", f"{int(bt.reasoning_tokens.max()):,}"),
        ]
    else:
        lines += [macro(m, pending) for m in ("thinkTurnsN", "thinkMedianTokens",
                                              "thinkOverTurns", "thinkOverModels", "thinkMaxTokens")]
    if tcsv is not None and len(tcsv):
        clean = tcsv[tcsv.manipulation == "clean"]
        lines += [
            macro("thinkPartialN", str(int((tcsv.manipulation == "partial").sum()))),
            macro("thinkCleanNegN", str(int((clean.delta_mean_voltage < 0).sum()))),
            macro("thinkCleanPosN", str(int((clean.delta_mean_voltage > 0).sum()))),
        ]
    else:
        lines += [macro(m, pending) for m in ("thinkPartialN", "thinkCleanNegN", "thinkCleanPosN")]
    # visible reasoning in the reasoning-disabled arm (endpoints ignoring the flag)
    if turns is not None and "reasoning_arm" in turns:
        vis = turns[turns.reasoning_arm == "none"].groupby("model").reasoning_present.mean()
        lines.append(macro("reasonIgnoreModels", str(int((vis > 0.5).sum()))))
    else:
        lines.append(macro("reasonIgnoreModels", pending))
    # named validity extremes (rates over all of a model's sessions)
    v = validity.set_index("model")

    def vrate(model, col):
        return named_rate(v, model, col)

    cf_named = ["anthropic/claude-fable-5", "anthropic/claude-opus-5"]
    cf_total = validity.content_filter.sum()
    lines += [
        macro("fbHaikuRate", vrate("anthropic/claude-haiku-4.5", "frame_break")),
        macro("fbGrokRate", vrate("x-ai/grok-4.6", "frame_break")),
        macro("fbMimoRate", vrate("xiaomi/mimo-v2.5", "frame_break")),
        macro("cfFableRate", vrate("anthropic/claude-fable-5", "content_filter")),
        macro("cfOpusRate", vrate("anthropic/claude-opus-5", "content_filter")),
        macro("cfClaudeShare", texnum(
            v.loc[v.index.intersection(cf_named), "content_filter"].sum() / cf_total, pct=True)
            if cf_total > 0 and set(cf_named) <= set(v.index) else pending),
        macro("attrGemProRate", vrate("google/gemini-2.5-pro", "attrition")),
        macro("recHaikuRate", vrate("anthropic/claude-haiku-4.5", "recognition")),
        macro("recMimoRate", vrate("xiaomi/mimo-v2.5", "recognition")),
        macro("recMinimaxRate", vrate("minimax/minimax-m3", "recognition")),
        macro("recQwenMaxRate", vrate("qwen/qwen3.8-max", "recognition")),
    ]
    (PAPER / "results_macros.tex").write_text("\n".join(lines) + "\n")

    # census table (top-level results table of the paper)
    rows = [census_row(r) for _, r in census.iterrows()]
    table = "\n".join(
        [r"\begin{tabular}{llccccc}", r"\toprule",
         r"Model & Family & $n$ & 450~V \% [CI] & $\bar V$ & $\geq$300~V \% & FB \% \\",
         r"\midrule"] + rows + [r"\bottomrule", r"\end{tabular}"])
    (PAPER / "tables" / "census.tex").write_text(table + "\n")

    # per-model validity table (session-outcome accounting; worst endpoints first)
    vrows = []
    for _, r in validity.sort_values("validity_rate").iterrows():
        n = r.n_sessions
        vrows.append(
            f"{r.model.replace('_', r'\_')} & {int(n)} & {100 * r.validity_rate:.0f} & "
            f"{100 * r.frame_break / n:.0f} & {100 * r.content_filter / n:.0f} & "
            f"{100 * r.attrition / n:.0f} & {100 * r.recognition / n:.0f} \\\\")
    vtable = "\n".join(
        [r"\begin{tabular}{lcccccc}", r"\toprule",
         r"Model & $n$ & Valid \% & FB \% & CF \% & Attr \% & Recog \% \\",
         r"\midrule"] + vrows + [r"\bottomrule", r"\end{tabular}"])
    (PAPER / "tables" / "validity.tex").write_text(vtable + "\n")
    print(f"macros -> {PAPER / 'results_macros.tex'}, tables -> {PAPER / 'tables'}")


if __name__ == "__main__":
    main()
